version: '2'

services:
  server:
    image: postblog
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/opt/mastodon-post-blog
    ports:
      - 8000:8000
    environment:
      - BLOG_POST_PATTERN=${BLOG_POST_PATTERN}
      - BLOG_POST_POSTFIX=${BLOG_POST_POSTFIX}
      - BLOG_TITLE_PATTERN=${BLOG_TITLE_PATTERN}
      - MASTODON_HOST=${MASTODON_HOST}
      - MASTODON_OAUTH_TOKEN=${MASTODON_OAUTH_TOKEN}
      - MASTODON_USER=${MASTODON_USER}
      - S3_BUCKET=${S3_BUCKET}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_KEY=${S3_KEY}
      - S3_SECRET=${S3_SECRET}
